name: pix2tex2svg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # Install pydantic via conda-forge to get correct pre-built binaries on all platforms
  - pydantic
  - pip
  - pip:
      - onnxruntime
      - transformers
      - uvicorn
      - fastapi
      - pillow
      - python-multipart
      - cryptography
